version: '3'
services:
  blog:
    image: wordpress:latest
    depends_on: 
      - db
    restart: always
    volumes:
      - wp_data:/var/www/html
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_db_pass
      WORDPRESS_DB_HOST: db:3306
  db:
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root_pass
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wp_user
        MYSQL_PASSWORD: wp_db_pass
volumes:
  wp_data:
  db_data:
  

